disabled_rules:
- trailing_newline
- opening_brace
- empty_count
- comma
- colon
- force_cast
- type_name
- variable_name_min_length
- trailing_semicolon
- force_try
- function_body_length
- nesting
- variable_name
- conditional_binding_cascade
- variable_name_max_length
- operator_whitespace
- control_statement
- legacy_constant
- line_length
- return_arrow_whitespace
- trailing_whitespace
- closing_brace
- statement_position
- type_body_length
- todo
- legacy_constructor
- valid_docs
- missing_docs
- file_length
- leading_whitespace
- vertical_whitespace

excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib

file_length:
- ignore_comment_only_lines: true

cyclomatic_complexity: 10
warning: 10
error: 10
ignores_case_statements: false

function_body_length:
warning: 300
error: 400

function_parameter_count: 10
warning: 10
error: 10
